### ISSUE TITLE
Description of a data set

### ISSUE THREAD

**Issue by love-freedom777** [DulanWirajith/Real-Tme-Bus-Arrival-Tme-Prediction-Model-using-Tensorflow-Lite#1]
Hello, is there any detailed documentation of the data？

**Comment by DulanWirajith** [comment]
This sample data set is obtained using our android application. Using the application we get real-time location. It have 
Bus No,Date,Time,Driver rating based on time,Driver rating based on decipline,Bus rating,Driver Age,Bus type,Longtide,Latitude,Start/End
We attach dummy data to Bus No, Driver rating based on time,Driver rating based on decipline,Bus rating,Driver Age.

**Comment by DulanWirajith** [comment]
This sample data set is obtained by using our android application. Using the application we get real-time location. It have
Bus No,Date,Time,Driver rating based on time,Driver rating based on decipline,Bus rating,Driver Age,Bus type,Longtide,Latitude,Start/End
We attach dummy data to Bus No, Driver rating based on time,Driver rating based on decipline,Bus rating,Driver Age.

**Comment by love-freedom777** [comment]
Thank you very much!
